development:
  adapter: postgresql
  encoding: unicode
  database: quora_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: quora_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: quora_production
  pool: 5
  timeout: 5000